FROM debian:sid
MAINTAINER Jeff Canas <jeffcanas13@gmail.com>

ADD https://dl.google.com/linux/direct/google-talkplugin_current_amd64.deb /src/google-talkplugin_current_amd64.deb

# Install Chrome
RUN echo 'deb http://httpredir.debian.org/debian testing main' >> /etc/apt/sources.list && \
        apt-get update && apt-get install -y \
        ca-certificates \
        curl \
        hicolor-icon-theme \
        libgl1-mesa-dri \
        libgl1-mesa-glx \
        libv4l-0 \
        -t testing \
        fonts-symbola \
        --no-install-recommends \
        && curl -sSL https://dl.google.com/linux/linux_signing_key.pub | apt-key add - \
        && echo "deb [arch=amd64] http://dl.google.com/linux/chrome/deb/ stable main" > /etc/apt/sources.list.d/google.list \

        && apt-get update && apt-get install -y \
        google-chrome-stable \
        --no-install-recommends \
        && dpkg -i '/src/google-talkplugin_current_amd64.deb' \
        && apt-get purge --auto-remove -y curl \
        && rm -rf /var/lib/apt/lists/* \
        && rm -rf /src/*.deb

COPY local.conf /etc/fonts/local.conf

# Autorun chrome
ENTRYPOINT [ "google-chrome" ]
CMD [ "--user-data-dir=/data" ]
